.test debian: &TEST-DEBIAN
  variables:
    FTPSYNC_CONF: |
      TO=root
      RSYNC=true
      RSYNC_HOST=localhost
      MIRRORNAME=localhost
      INFO_MAINTAINER="Admins <admins@example.com>, Person <person@example.com>"
      INFO_SPONSOR="Example <https://example.com>"
      INFO_COUNTRY=DE
      INFO_LOCATION=Example
      INFO_THROUGHPUT=10Gb
    RUNMIRRORS_CONF: |
      KEYFILE=~/key
    SSH_KEY: |
  script:
    - echo "$FTPSYNC_CONF" > etc/ftpsync.conf
    - echo "$RUNMIRRORS_CONF" > etc/runmirrors.conf
    - echo "$SSH_KEY" > ~/key
    - bin/ftpsync -T test || e_ftpsync=$?
    - bin/runmirrors || e_runmirrors=$?
    - ls -alR log root
    - cat root/project/trace/localhost
    - cat log/ftpsync.log* || true
    - cat log/runmirrors.log* || true
    - '[[ $e_ftpsync -eq 0 ]] || exit $e_ftpsync'
    - '[[ $e_runmirrors -eq 0 ]] || exit $e_runmirrors'

    - apt-get update
    - apt-get install --yes --no-install-recommends dpkg-dev git make
    - make
    - echo "$FTPSYNC_CONF" > etc/ftpsync.install-tar.conf
    - echo "$RUNMIRRORS_CONF" > etc/runmirrors.install-tar.conf
    - bash bin/ftpsync.install-tar -T test || e_ftpsync=$?
    - bash bin/runmirrors.install-tar || e_runmirrors=$?
    - cat root/project/trace/localhost
    - '[[ $e_ftpsync -eq 0 ]] || exit $e_ftpsync'
    - '[[ $e_runmirrors -eq 0 ]] || exit $e_runmirrors'

test stretch:
  <<: *TEST-DEBIAN
  image: debian:stretch

test wheezy:
  <<: *TEST-DEBIAN
  image: debian:wheezy
