.test debian: &TEST-DEBIAN
  script:
    - apt-get update > /dev/null
    - DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends curl git rsync > /dev/null

    - cd test/simple
    - ln -s $(pwd)/rsyncd /rsyncd
    - echo "" > ~/key

    - rsync --daemon --log-file $(pwd)/log/rsyncd.log --config $(pwd)/etc/rsyncd.conf
    - bin/ftpsync -T test || e_ftpsync=$?
    - bin/runmirrors || e_runmirrors=$?
    - ls -alR log root
    - cat root/project/trace/localhost
    - cat log/ftpsync.log* || true
    - cat log/runmirrors.log* || true
    - '[[ $e_ftpsync -eq 0 ]] || exit $e_ftpsync'
    - '[[ $e_runmirrors -eq 0 ]] || exit $e_runmirrors'
  artifacts:
    paths:
      - test/simple/log
      - test/simple/root
    when: always

test stretch:
  <<: *TEST-DEBIAN
  image: debian:stretch

test wheezy:
  <<: *TEST-DEBIAN
  image: debian:wheezy

.test debian security: &TEST-DEBIAN-SECURITY
  script:
    - apt-get update > /dev/null
    - DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends curl git rsync > /dev/null

    - cd test/security

    - bin/ftpsync-cron security
    - bin/ftpsync-cron security
    - ls -alR log root
    - cat root/project/trace/localhost
    - cat log/ftpsync.log* || true
  artifacts:
    paths:
      - test/security/log
      - test/security/root
    when: always

test stretch security:
  <<: *TEST-DEBIAN-SECURITY
  image: debian:stretch

.test redhat: &TEST-REDHAT
  script:
    - yum install -y curl git rsync > /dev/null

    - cd test/simple
    - ln -s $(pwd)/rsyncd /rsyncd
    - echo "" > ~/key

    - rsync --daemon --log-file $(pwd)/log/rsyncd.log --config $(pwd)/etc/rsyncd.conf
    - bin/ftpsync -T test || e_ftpsync=$?
    - bin/runmirrors || e_runmirrors=$?
    - ls -alR log root
    - cat root/project/trace/localhost
    - cat log/ftpsync.log* || true
    - cat log/runmirrors.log* || true
    - '[[ $e_ftpsync -eq 0 ]] || exit $e_ftpsync'
    - '[[ $e_runmirrors -eq 0 ]] || exit $e_runmirrors'

test centos6:
  <<: *TEST-REDHAT
  image: centos:centos6

test centos7:
  <<: *TEST-REDHAT
  image: centos:centos7
