ftpsync:
  image: debian:stable
  variables:
    FTPSYNC_CONF: |
      TO=root
      RSYNC=true
      RSYNC_HOST=localhost
      MIRRORNAME=localhost
      INFO_MAINTAINER="Admins <admins@example.com>, Person <person@example.com>"
      INFO_SPONSOR="Example <https://example.com>"
      INFO_COUNTRY=DE
      INFO_LOCATION=Example
      INFO_THROUGHPUT=10Gb
  script:
    - echo "$FTPSYNC_CONF" > etc/ftpsync.conf
    - bin/ftpsync || e=$?
    - ls -alR log root
    - cat root/project/trace/localhost
    - cat log/ftpsync.log* || true
    - exit $e
